from enum import Enum


class ChatServiceConstants(Enum):
    """
    Constants used throughout the chat service for configuration and identification.
    These constants include logger names, service IDs, and default settings.
    """
    LOGGER_NAME = "web_api.chat_service"
    CHAT_SERVICE_ID = "azure-openai"
    EMBEDDING_SERVICE_ID = "azure_embedding"
    DEFAULT_TEMPERATURE = 0


class EnvironmentVariables(Enum):
    """
    Environment variables used for configuration.
    """
    AZURE_BLOB_KEY = "AZURE_BLOB_KEY"
    AZURE_BLOB_URL = "AZURE_BLOB_URL"
    AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT = "AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT"
    AZURE_DOCUMENT_INTELLIGENCE_KEY = "AZURE_DOCUMENT_INTELLIGENCE_KEY"
    AZURE_SEARCH_SERVICE_ENDPOINT = "AZURE_SEARCH_SERVICE_ENDPOINT"
    AZURE_SEARCH_NUREG_INDEX_NAME = "AZURE_SEARCH_NUREG_INDEX_NAME"
    AZURE_SEARCH_REPORTABILITY_MANUAL_INDEX_NAME = "AZURE_SEARCH_REPORTABILITY_MANUAL_INDEX_NAME"
    AZURE_SEARCH_TECHSPEC_INDEX_NAME = "AZURE_SEARCH_TECHSPEC_INDEX_NAME"
    AZURE_SEARCH_UFSAR_INDEX_NAME = "AZURE_SEARCH_UFSAR_INDEX_NAME"
    AZURE_SEARCH_API_KEY = "AZURE_SEARCH_API_KEY"  # pragma: allowlist secret
    AZURE_EMBEDDING_DEPLOYMENT = "AZURE_EMBEDDING_DEPLOYMENT"
    AZURE_OPENAI_ENDPOINT = "AZURE_OPENAI_ENDPOINT"
    AZURE_OPENAI_DEPLOYMENT = "AZURE_OPENAI_DEPLOYMENT"
    AZURE_OPENAI_API_VERSION = "AZURE_OPENAI_API_VERSION"
    OTEL_EXPORTER_OTLP_ENDPOINT = "OTEL_EXPORTER_OTLP_ENDPOINT"
    AZURE_OPENAI_API_KEY = "AZURE_OPENAI_API_KEY"  # pragma: allowlist secret
    STREAM_BUFFER_SIZE = "STREAM_BUFFER_SIZE"
    SAS_TOKEN_EXPIRATIONS_DAYS = "SAS_TOKEN_EXPIRATIONS_DAYS"
    ORCHESTRATION_TYPE = "ORCHESTRATION_TYPE"
